services:
  db:
    image: postgres:17-alpine
    container_name: room_booking_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PSWD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    container_name: room_booking_ap
    build: .
    ports:
      - "8080:8000"
    environment:
      - ENVIRONMENT=development
      - DB_USER=${DB_USER}
      - DB_PSWD=${DB_PSWD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: